In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [21]:
pip install xlwt

Requirement already satisfied: xlwt in /opt/anaconda3/lib/python3.8/site-packages (1.3.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
dataFrame = pd.read_excel('Question Set - FB_Page_Decoder_Data_Analyst (1).xlsx')
dataFrame.head()

   Unnamed: 0                                         Unnamed: 1
0         NaN      Please Note  - You may have to clean the data
1         NaN                                                NaN
2         1.0  Which User is interacting with the page the hi...
3         2.0  In Post_List, you have a column called Post_Te...
4         3.0  In Comments, you have a column called comment ...

In [23]:
dataFrame_post_list = pd.read_excel('Question Set - FB_Page_Decoder_Data_Analyst (1).xlsx',sheet_name='Post_List')

In [24]:
dataFrame_post_list.head()

,post_date,Post_Text,Post_Embedded_URL,Post_URL
0,2020-07-22,"Dear Shankra Family, \n first of all, we want ...",http://bit.ly/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=30...
1,2020-10-30,Walking towards the future with the strongest ...,b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...
2,2020-10-27,"The Mesolcina Mountain Chain, home to Shankra ...",b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...
3,2020-10-24,"We believe in pure music, freely expressed by ...",b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...
4,2020-10-21,"The beating heart of our Valley, Shankra Stage...",b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...

In [9]:
dataFrame_Post_List.head()

,post_date,Post_Text,Post_Embedded_URL,Post_URL
0,2020-07-22,"Dear Shankra Family, \n first of all, we want ...",http://bit.ly/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=30...
1,2020-10-30,Walking towards the future with the strongest ...,b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...
2,2020-10-27,"The Mesolcina Mountain Chain, home to Shankra ...",b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...
3,2020-10-24,"We believe in pure music, freely expressed by ...",b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...
4,2020-10-21,"The beating heart of our Valley, Shankra Stage...",b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...

In [10]:
dataFrame_Comments = pd.read_excel('Question Set - FB_Page_Decoder_Data_Analyst (1).xlsx',sheet_name='Comments')

In [11]:
dataFrame_Comments.head()

,Name,People_URL,Page_Or_Person,Post_URL,Comment
0,Andreas Kenotaph,https://m.facebook.com/andreas.inkmann,Person,https://m.facebook.com/story.php?story_fbid=30...,Felt good to give you something back for all t...
1,Top fan\nLuca Maccarone,https://m.facebook.com/luca.maccarone.7,Person,https://m.facebook.com/story.php?story_fbid=30...,I already canâ€™t wait for next year ðŸ˜ It w...
2,Lia Silva,https://m.facebook.com/alma.lilly.aho,Person,https://m.facebook.com/story.php?story_fbid=30...,Is the line up remaining the same?ðŸ¦‹
3,Author\nShankra Festival,https://m.facebook.com/shankrafestival/,Page,https://m.facebook.com/story.php?story_fbid=30...,yes :)
4,Author\nShankra Festival,https://m.facebook.com/shankrafestival/,Page,https://m.facebook.com/story.php?story_fbid=30...,"Yes, tickets for the 2020's edition will grant..."

In [12]:
dataFrame_Reactions = pd.read_excel('Question Set - FB_Page_Decoder_Data_Analyst (1).xlsx',sheet_name='Shares')

In [13]:
dataFrame_Reactions

,Shares_By,Shares_By_URL,Page_Or_Person,Total_Share,Post_URL
0,Eric Keriguy,https://m.facebook.com/eric.keriguy.7,Person,56 shares,https://m.facebook.com/story.php?story_fbid=30...
1,Psytranceworldwidemagazine,https://m.facebook.com/psytranceworldwidemagaz...,Page,56 shares,https://m.facebook.com/story.php?story_fbid=30...
2,Dj Kalanio,https://m.facebook.com/kalanio44/,Page,56 shares,https://m.facebook.com/story.php?story_fbid=30...
3,Silvia Sey,https://m.facebook.com/silvia.mandelli.73,Person,56 shares,https://m.facebook.com/story.php?story_fbid=30...
4,Giovanni Ricciardi,https://m.facebook.com/giovanniricciardijunior,Person,56 shares,https://m.facebook.com/story.php?story_fbid=30...
...,...,...,...,...,...
236,Pao Garo,https://m.facebook.com/pao.garoush,Person,127 shares,https://m.facebook.com/story.php?story_fbid=24...
237,Lella Toma,https://m.facebook.com/LellaTattooando,Person,127 shares,https://m.facebook.com/story.php?story_fbid=24...
238,Kim Pixii Lopes,https://m.facebook.com/PsyPixii,Person,127 shares,https://m.facebook.com/story.php?story_fbid=24...
239,Dennis Boarin,https://m.facebook.com/dennis.boarin,Person,127 shares,https://m.facebook.com/story.php?story_fbid=24...
240,Brittany Brittou Bohaer,https://m.facebook.com/brittou.BohaerGouaich,Person,127 shares,https://m.facebook.com/story.php?story_fbid=24...

In [14]:
dataFrame_Shares = pd.read_excel('Question Set - FB_Page_Decoder_Data_Analyst (1).xlsx',sheet_name='Shares')

In [15]:
dataFrame_Shares.head()

,Shares_By,Shares_By_URL,Page_Or_Person,Total_Share,Post_URL
0,Eric Keriguy,https://m.facebook.com/eric.keriguy.7,Person,56 shares,https://m.facebook.com/story.php?story_fbid=30...
1,Psytranceworldwidemagazine,https://m.facebook.com/psytranceworldwidemagaz...,Page,56 shares,https://m.facebook.com/story.php?story_fbid=30...
2,Dj Kalanio,https://m.facebook.com/kalanio44/,Page,56 shares,https://m.facebook.com/story.php?story_fbid=30...
3,Silvia Sey,https://m.facebook.com/silvia.mandelli.73,Person,56 shares,https://m.facebook.com/story.php?story_fbid=30...
4,Giovanni Ricciardi,https://m.facebook.com/giovanniricciardijunior,Person,56 shares,https://m.facebook.com/story.php?story_fbid=30...

In [25]:
# Now for cobine dataframes....in stack form


# pandas provides function Concatenate or "Stack" a list of pd.dataFrames


# syntax : pd.concat([amex , nasdaq , nyse ] )

In [26]:
dataFrame = pd.concat([dataFrame_Post_List,dataFrame_Comments,dataFrame_Reactions,dataFrame_Shares])

In [39]:
dataFrame.head(100)

,post_date,Post_Text,Post_Embedded_URL,Post_URL,Name,People_URL,Page_Or_Person,Comment,Shares_By,Shares_By_URL,Total_Share
0,2020-07-22,"Dear Shankra Family, \n first of all, we want ...",http://bit.ly/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=30...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-10-30,Walking towards the future with the strongest ...,b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-10-27,"The Mesolcina Mountain Chain, home to Shankra ...",b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-10-24,"We believe in pure music, freely expressed by ...",b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-10-21,"The beating heart of our Valley, Shankra Stage...",b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
67,NaT,NaN,NaN,https://m.facebook.com/story.php?story_fbid=33...,Paul Kieliseck,https://m.facebook.com/kalanio.kieliszek,Person,i loved,NaN,NaN,NaN
68,NaT,NaN,NaN,https://m.facebook.com/story.php?story_fbid=33...,Top fan\nAndreas Deets,https://m.facebook.com/andreas.deets,Person,Andreas Wein Angie Tralali DE Nise MA Ier Laur...,NaN,NaN,NaN
69,NaT,NaN,NaN,https://m.facebook.com/story.php?story_fbid=33...,Top fan\nAndreas Deets,https://m.facebook.com/andreas.deets,Person,Pray for it! â™¥ï¸ We all need music back again,NaN,NaN,NaN
70,NaT,NaN,NaN,https://m.facebook.com/story.php?story_fbid=33...,Ariel Haymovich,https://m.facebook.com/ariel.haymovich,Person,ðŸ’šðŸŽ©ðŸ‘»ðŸ¤¹â€â™‚ï¸,NaN,NaN,NaN
71,NaT,NaN,NaN,https://m.facebook.com/story.php?story_fbid=33...,MAeff YU,https://m.facebook.com/profile.php,Person,Andreas Deets auf keinen Fall verbieten.,NaN,NaN,NaN

In [29]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1251 entries, 0 to 240
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   post_date          28 non-null     datetime64[ns]
 1   Post_Text          28 non-null     object
 2   Post_Embedded_URL  21 non-null     object
 3   Post_URL           1251 non-null   object
 4   Name               741 non-null    object
 5   People_URL         741 non-null    object
 6   Page_Or_Person     1223 non-null   object
 7   Comment            732 non-null    object
 8   Shares_By          482 non-null    object
 9   Shares_By_URL      482 non-null    object
 10  Total_Share        482 non-null    object
dtypes: datetime64[ns](1), object(10)
memory usage: 117.3+ KB

In [31]:
dataFrame.shapee

(1251, 11)

In [34]:
dataFrame.isna().sum()

post_date            1223
Post_Text            1223
Post_Embedded_URL    1230
Post_URL                0
Name                  510
People_URL            510
Page_Or_Person         28
Comment               519
Shares_By             769
Shares_By_URL         769
Total_Share           769
dtype: int64

In [40]:
print(dataFrame['Page_Or_Person']).head(10)

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
        ...
236    Person
237    Person
238    Person
239    Person
240    Person
Name: Page_Or_Person, Length: 1251, dtype: object

AttributeError: 'NoneType' object has no attribute 'head'

In [ ]:
missing_value_formats = ["NAN","?","NA","n/a", "na", "--"]
# dataFrame = pd.read("employees.csv", na_values = missing_value_formats)

def make_int(i):
    try:
        return int(i)
    except:
        return pd.np.nan

# apply make_int function to the entire series using map
df['Name'] = df['Name'].map(make_int)
print(dataFrame['Name'].head())

In [41]:
dataFrame.head()

,post_date,Post_Text,Post_Embedded_URL,Post_URL,Name,People_URL,Page_Or_Person,Comment,Shares_By,Shares_By_URL,Total_Share
0,2020-07-22,"Dear Shankra Family, \n first of all, we want ...",http://bit.ly/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=30...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-10-30,Walking towards the future with the strongest ...,b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-10-27,"The Mesolcina Mountain Chain, home to Shankra ...",b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-10-24,"We believe in pure music, freely expressed by ...",b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-10-21,"The beating heart of our Valley, Shankra Stage...",b.link/ShankraTickets2021,https://m.facebook.com/story.php?story_fbid=33...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1251 entries, 0 to 240
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   post_date          28 non-null     datetime64[ns]
 1   Post_Text          28 non-null     object
 2   Post_Embedded_URL  21 non-null     object
 3   Post_URL           1251 non-null   object
 4   Name               741 non-null    object
 5   People_URL         741 non-null    object
 6   Page_Or_Person     1223 non-null   object
 7   Comment            732 non-null    object
 8   Shares_By          482 non-null    object
 9   Shares_By_URL      482 non-null    object
 10  Total_Share        482 non-null    object
dtypes: datetime64[ns](1), object(10)
memory usage: 117.3+ KB

In [44]:
# NaN values are marked True
print(dataFrame['Name'].isnull().head(10))
# NaN values are marked False 
print(dataFrame['Name'].notnull().head(10))

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: Name, dtype: bool
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Name, dtype: bool

In [45]:
# notnull will return False for all NaN values
null_filter = dataFrame['Name'].notnull()
# prints only those rows where null_filter is True
print(dataFrame[null_filter])

    post_date Post_Text Post_Embedded_URL  \
0         NaT       NaN               NaN
1         NaT       NaN               NaN
2         NaT       NaN               NaN
3         NaT       NaN               NaN
4         NaT       NaN               NaN
..        ...       ...               ...
736       NaT       NaN               NaN
737       NaT       NaN               NaN
738       NaT       NaN               NaN
739       NaT       NaN               NaN
740       NaT       NaN               NaN

                                              Post_URL  \
0    https://m.facebook.com/story.php?story_fbid=30...
1    https://m.facebook.com/story.php?story_fbid=30...
2    https://m.facebook.com/story.php?story_fbid=30...
3    https://m.facebook.com/story.php?story_fbid=30...
4    https://m.facebook.com/story.php?story_fbid=30...
..                                                 ...
736  https://m.facebook.com/story.php?story_fbid=24...
737  https://m.facebook.com/story.php?story_fbid=24...
738  https://m.facebook.com/story.php?story_fbid=24...
739  https://m.facebook.com/story.php?story_fbid=24...
740  https://m.facebook.com/story.php?story_fbid=24...

                               Name  \
0                  Andreas Kenotaph
1           Top fan\nLuca Maccarone
2                         Lia Silva
3          Author\nShankra Festival
4          Author\nShankra Festival
..                              ...
736      Psytranceworldwidemagazine
737  Top fan\nSonja Ivory Carangelo
738                    Lotus Spirit
739            Benedikt Christopeit
740                       Ruben Ook

                                            People_URL Page_Or_Person  \
0               https://m.facebook.com/andreas.inkmann         Person
1              https://m.facebook.com/luca.maccarone.7         Person
2                https://m.facebook.com/alma.lilly.aho         Person
3              https://m.facebook.com/shankrafestival/           Page
4              https://m.facebook.com/shankrafestival/           Page
..                                                 ...            ...
736  https://m.facebook.com/psytranceworldwidemagaz...           Page
737                  https://m.facebook.com/sonja.ibeh         Person
738                 https://m.facebook.com/profile.php         Person
739                https://m.facebook.com/bchristopeit         Person
740                   https://m.facebook.com/ruben.ook         Person

                                               Comment Shares_By  \
0    Felt good to give you something back for all t...       NaN
1    I already canâ€™t wait for next year ðŸ˜ It w...       NaN
2               Is the line up remaining the same?ðŸ¦‹       NaN
3                                               yes :)       NaN
4    Yes, tickets for the 2020's edition will grant...       NaN
..                                                 ...       ...
736  Retro setðŸ˜ðŸ˜ðŸ˜ðŸ˜ðŸ˜ðŸ˜ mega nice ðŸ...       NaN
737                                               ðŸ¤©       NaN
738                                       ðŸ˜ŠðŸ¤©ðŸ˜Š       NaN
739                                               ðŸ‘       NaN
740                                               Gaan       NaN

    Shares_By_URL Total_Share
0             NaN         NaN
1             NaN         NaN
2             NaN         NaN
3             NaN         NaN
4             NaN         NaN
..            ...         ...
736           NaN         NaN
737           NaN         NaN
738           NaN         NaN
739           NaN         NaN
740           NaN         NaN

[741 rows x 11 columns]

In [46]:
print(dataFrame.isnull().values.any())

True

In [47]:
print(dataFrame.isnull().sum())

post_date            1223
Post_Text            1223
Post_Embedded_URL    1230
Post_URL                0
Name                  510
People_URL            510
Page_Or_Person         28
Comment               519
Shares_By             769
Shares_By_URL         769
Total_Share           769
dtype: int64

In [50]:
#1. Function to replace NAN values with mode value
def impute_nan_most_frequent_category(DataFrame,ColName):
    # .mode()[0] - gives first category name
     most_frequent_category=DataFrame[ColName].mode()[0]
    
    # replace nan values with most occured category
     DataFrame[ColName + "_Imputed"] = DataFrame[ColName]
     DataFrame[ColName + "_Imputed"].fillna(most_frequent_category,inplace=True)
#2. Call function to impute most occured category
for Columns in ['post_date','Post_Text','Post_Embedded_URL','Name','People_URL','Page_Or_Person','Comment','Shares_By','Shares_By_URL','Total_Share']:
    impute_nan_most_frequent_category(dataFrame,Columns)
    
# Display imputed result
dataFrame[['post_date','Post_Text','Post_Embedded_URL','Name','People_URL','Page_Or_Person','Comment','Shares_By','Shares_By_URL','Total_Share']].head(10)
#3. Drop actual columns
dataFrame = dataFrame.drop(['post_date','Post_Text','Post_Embedded_URL','Name','People_URL','Page_Or_Person','Comment','Shares_By','Shares_By_URL','Total_Share'], axis = 1)

In [51]:
dataFrame.head()

,Post_URL,post_date_Imputed,Post_Text_Imputed,Post_Embedded_URL_Imputed,Name_Imputed,People_URL_Imputed,Page_Or_Person_Imputed,Comment_Imputed,Shares_By_Imputed,Shares_By_URL_Imputed,Total_Share_Imputed
0,https://m.facebook.com/story.php?story_fbid=30...,2020-07-22,"Dear Shankra Family, \n first of all, we want ...",http://bit.ly/ShankraTickets2021,Author\nShankra Festival,https://m.facebook.com/profile.php,Person,media1.tenor.co\nmedia1.tenor.co,Il Kahuixx,https://m.facebook.com/profile.php,937 shares
1,https://m.facebook.com/story.php?story_fbid=33...,2020-10-30,Walking towards the future with the strongest ...,b.link/ShankraTickets2021,Author\nShankra Festival,https://m.facebook.com/profile.php,Person,media1.tenor.co\nmedia1.tenor.co,Il Kahuixx,https://m.facebook.com/profile.php,937 shares
2,https://m.facebook.com/story.php?story_fbid=33...,2020-10-27,"The Mesolcina Mountain Chain, home to Shankra ...",b.link/ShankraTickets2021,Author\nShankra Festival,https://m.facebook.com/profile.php,Person,media1.tenor.co\nmedia1.tenor.co,Il Kahuixx,https://m.facebook.com/profile.php,937 shares
3,https://m.facebook.com/story.php?story_fbid=33...,2020-10-24,"We believe in pure music, freely expressed by ...",b.link/ShankraTickets2021,Author\nShankra Festival,https://m.facebook.com/profile.php,Person,media1.tenor.co\nmedia1.tenor.co,Il Kahuixx,https://m.facebook.com/profile.php,937 shares
4,https://m.facebook.com/story.php?story_fbid=33...,2020-10-21,"The beating heart of our Valley, Shankra Stage...",b.link/ShankraTickets2021,Author\nShankra Festival,https://m.facebook.com/profile.php,Person,media1.tenor.co\nmedia1.tenor.co,Il Kahuixx,https://m.facebook.com/profile.php,937 shares

In [52]:
print(dataFrame.isnull().sum())

Post_URL                     0
post_date_Imputed            0
Post_Text_Imputed            0
Post_Embedded_URL_Imputed    0
Name_Imputed                 0
People_URL_Imputed           0
Page_Or_Person_Imputed       0
Comment_Imputed              0
Shares_By_Imputed            0
Shares_By_URL_Imputed        0
Total_Share_Imputed          0
dtype: int64